DROP USER TP CASCADE;
Drop TABLE DET;
Drop TABLE PRO;
Drop TABLE COM;
Drop TABLE FOU;
Drop TABLE CLI;

ALTER SESSION SET CONTAINER=XEPDB1;
CREATE USER TP IDENTIFIED BY oracle;
GRANT ALL PRIVILEGES TO TP;
CONNECT TP/oracle;


CREATE TABLE CLI (
 NumCli number(5) PRIMARY KEY,
 NomCli char(20),
 Pays char(30),
 Solde NUMBER(10,2));

INSERT INTO CLI VALUES(1,'Joe','FR',10000);

SELECT * from CLI;